
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HomePC
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        u = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HomePC\\Desktop\\Create Your Business Card   Design Studio.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setText("User Name:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(140, 60, 70, 14);

        jLabel3.setText("Password:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 90, 80, 14);

        u.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel2.add(u);
        u.setBounds(210, 60, 90, 19);
        jPanel2.add(pwd);
        pwd.setBounds(210, 90, 90, 20);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LOGIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(180, 140, 80, 23);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(30, 270, 73, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\Create Your Business Card   Design Studio.png")); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 540, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String u1=u.getText();
        String pwd1=new String(pwd.getPassword());
        if(u1.equalsIgnoreCase("vyshakhmanoj")&&pwd1.equals("ipproject")){
            JOptionPane.showMessageDialog(this,"Welocme "+u1+" To Mobile Homes");
            tech login=new tech();
            login.setVisible(true);
            this.dispose();}
        else if(u1.equalsIgnoreCase("DenioShaji")&&pwd1.equals("ipproject1")){
            JOptionPane.showMessageDialog(this,"Welocme "+u1+" "+"To Mobile Homes");
            tech login=new tech();
            login.setVisible(true);
            this.dispose();}
        else if(u1.equalsIgnoreCase("SujaySs")&&pwd1.equals("ipproject2")){
            JOptionPane.showMessageDialog(this,"Welocme "+u1+" To Mobile Homes");
            tech login=new tech();
            login.setVisible(true);
            this.dispose();}
        else if(u1.equalsIgnoreCase("MelvinMathew")&&pwd1.equals("ipproject3")){
            JOptionPane.showMessageDialog(this,"Welocme "+u1+" To Mobile Homes");
            tech login=new tech();
            login.setVisible(true);
            this.dispose();}

        else
        JOptionPane.showMessageDialog(this,"Incorrect Username or Password"+"\n"+"Try Again");
        pwd.setText("");
        u.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField u;
    // End of variables declaration//GEN-END:variables
}
