
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HomePC
 */
public class tech extends javax.swing.JFrame {
String d="PH-";
int billno=100;
    /**
     * Creates new form tech
     */
    public tech() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        bd = new javax.swing.JComboBox();
        res = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bill = new javax.swing.JTextField();
        col = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sg = new javax.swing.JCheckBox();
        cover = new javax.swing.JCheckBox();
        hph = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        c1 = new javax.swing.JLabel();
        acc = new javax.swing.JPanel();
        c = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        hp1 = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ne = new javax.swing.JButton();
        ba = new javax.swing.JButton();
        des1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cm = new javax.swing.JTextField();
        ca = new javax.swing.JTextField();
        cp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        sg1 = new javax.swing.JTextField();
        hp2 = new javax.swing.JTextField();
        co1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mobile Homes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        bd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SAMSUNG", "APPLE", "HTC", "MICROSOFT" }));
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });

        res.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GALAXY S6", "GALAXY S5", "GALAXY S4" }));
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });

        jLabel1.setText("BILL NUMBER");

        jLabel2.setText("CUSTOMER NAME");

        jLabel3.setText("BRAND");

        jLabel4.setText("MODEL");

        bill.setEditable(false);
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        col.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "WHITE", "BLACK", "SILVER" }));
        col.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colActionPerformed(evt);
            }
        });

        jLabel6.setText("COLOR");

        jLabel7.setText("ACCESSORIES");

        sg.setText("Screen Guard");
        sg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sgItemStateChanged(evt);
            }
        });
        sg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sgMouseClicked(evt);
            }
        });
        sg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgActionPerformed(evt);
            }
        });
        sg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sgKeyReleased(evt);
            }
        });

        cover.setText("Cover");
        cover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coverActionPerformed(evt);
            }
        });

        hph.setText("Head Phone");
        hph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hphActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone Image", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        acc.setBackground(new java.awt.Color(255, 255, 255));
        acc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accessories", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        c.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
        });

        s1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s1MouseClicked(evt);
            }
        });

        c2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                c2MousePressed(evt);
            }
        });

        e.setText("            ");

        hp1.setDoubleBuffered(true);

        h1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        h1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                h1MousePressed(evt);
            }
        });

        h2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        h2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                h2MousePressed(evt);
            }
        });

        h3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        h3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                h3MousePressed(evt);
            }
        });

        e3.setText("       ");

        javax.swing.GroupLayout accLayout = new javax.swing.GroupLayout(acc);
        acc.setLayout(accLayout);
        accLayout.setHorizontalGroup(
            accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accLayout.createSequentialGroup()
                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(e))
                    .addGroup(accLayout.createSequentialGroup()
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hp1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(h1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(h3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(accLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        accLayout.setVerticalGroup(
            accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(accLayout.createSequentialGroup()
                        .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hp1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(e)
                        .addGap(16, 16, 16))
                    .addGroup(accLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(e3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel8.setText("jLabel8");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(10, 11, 59, 46);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIPTION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        ne.setText("NEXT");
        ne.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        ne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neActionPerformed(evt);
            }
        });

        ba.setText("BACK");
        ba.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        ba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(ba, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(ne, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addComponent(des1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(des1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ne)
                    .addComponent(ba)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 204), null, new java.awt.Color(102, 102, 0)));

        jLabel9.setText("COST OF THE MOBILE:");

        jLabel10.setText("COST OF THE ACCESSORIES:");

        jLabel5.setText("COST OF THE PRODUCT:");

        cm.setEditable(false);
        cm.setText("50000");

        ca.setEditable(false);

        cp.setEditable(false);
        cp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cm)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LOG OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        clear.setText("NEXT CUSTOMER");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        sg1.setEditable(false);
        sg1.setText("0");
        sg1.setToolTipText("cost of screen guard");

        hp2.setEditable(false);
        hp2.setText("0");
        hp2.setToolTipText("cost of headphone");
        hp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hp2ActionPerformed(evt);
            }
        });

        co1.setEditable(false);
        co1.setText("0");
        co1.setToolTipText("cost of cover");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\Create Your Business Card   Design Studio 2.png")); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\Create Your Business Card   Design Studi5.png")); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\Create Your Business Card   Design Studi5.1.png")); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(198, 198, 198)
                                        .addComponent(co1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(sg1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105)))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(sg)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(hph)
                                            .addGap(18, 18, 18)
                                            .addComponent(cover, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(hp2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bill, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(cn))))
                            .addGap(8, 8, 8)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(89, 89, 89)
                        .addComponent(clear)
                        .addGap(35, 35, 35)))
                .addComponent(acc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(156, 156, 156))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(acc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sg)
                                    .addComponent(hph)
                                    .addComponent(cover))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(co1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(clear))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rg.png"));
       hp1.setVisible(false);
       h1.setEnabled(false);   h2.setEnabled(false);   h3.setEnabled(false);   c2.setEnabled(false);   c.setEnabled(false);
       ba.setEnabled(false);
       c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6w.jpg"));
    }//GEN-LAST:event_formWindowOpened

    private void h3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h3MouseClicked
sg.setEnabled(true);  cover.setEnabled(true);           if(res.getSelectedIndex()>=0){
             
            String md1=(String)(bd.getSelectedItem());

            if(md1.equalsIgnoreCase("samsung"))
            { hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s2.jpg"));
                e.setText("");hp2.setText("350");
            }
            if(md1.equalsIgnoreCase("htc"))
            {hp2.setText("200");
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\hp1.jpg"));e.setText("");
            }

            if(md1.equalsIgnoreCase("apple"))
            {hp2.setText("850");
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i3.jpg"));
                e.setText("");

            }
            if(md1.equalsIgnoreCase("microsoft"))
            {
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\hp1.jpg"));
hp2.setText("200");
                e.setText("");

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_h3MouseClicked

    private void h2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h2MouseClicked
sg.setEnabled(true);  cover.setEnabled(true);           if(res.getSelectedIndex()>=0){
          
            String md1=(String)(bd.getSelectedItem());

            if(md1.equalsIgnoreCase("samsung"))
            { hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s3.jpg"));
                hp2.setText("350");
            }
            if(md1.equalsIgnoreCase("htc"))
            {
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\hp2.jpg"));hp2.setText("200");
            }

            if(md1.equalsIgnoreCase("apple"))
            {
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4.jpg"));
               hp2.setText("850");

            }
            if(md1.equalsIgnoreCase("microsoft"))
            {
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\hp2.jpg"));

               hp2.setText("200");

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_h2MouseClicked

    private void h1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h1MouseClicked
sg.setEnabled(true);  cover.setEnabled(true);       if(res.getSelectedIndex()>=0){
           
            String md1=(String)(bd.getSelectedItem());

            if(md1.equalsIgnoreCase("samsung"))
            { hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s4.jpg"));
                hp2.setText("350");
            }
            if(md1.equalsIgnoreCase("htc"))
            {hp2.setText("200");
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\htc.jpg"));e.setText("");
            }

            if(md1.equalsIgnoreCase("apple"))
            {hp2.setText("850");
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i1.jpg"));
                e.setText("");

            }
            if(md1.equalsIgnoreCase("microsoft"))
            {hp2.setText("200");
                hp1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\htc.jpg"));

                e.setText("");

            }
        }

    }//GEN-LAST:event_h1MouseClicked

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
sg.setEnabled(true);
    hph.setEnabled(true);
     if(res.getSelectedIndex()>=0){if(cover.isSelected()==true){

            String md1=(String)(res.getSelectedItem());

            if(md1.equalsIgnoreCase("GALAXY S6"))
            { c2.setIcon(new ImageIcon(""));
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6c3.jpg"));
               e3.setIcon(new ImageIcon(""));    co1.setText("500");  }
            if(md1.equalsIgnoreCase("GALAXY S5"))
            {     e3.setIcon(new ImageIcon(""));  c2.setIcon(new ImageIcon(""));co1.setText("600");
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss5c2.jpg"));
            }
            if(md1.equalsIgnoreCase("GALAXY S4"))
            { e3.setIcon(new ImageIcon(""));  c2.setIcon(new ImageIcon(""));co1.setText("400");
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss4c3.jpg"));
            }
            if(md1.equalsIgnoreCase("iPhone 6s"))
            {co1.setText("800");
                e3.setIcon(new ImageIcon(""));  c2.setIcon(new ImageIcon(""));
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6c1.jpg"));

            }
            if(md1.equalsIgnoreCase("iPhone 5s"))
            { e3.setIcon(new ImageIcon("")); c2.setIcon(new ImageIcon(""));co1.setText("700");
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5c2.jpg"));
            }
            if(md1.equalsIgnoreCase("iPhone 4s"))
            {e3.setIcon(new ImageIcon(""));  c2.setIcon(new ImageIcon(""));co1.setText("650");
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4c2.jpg"));

            }
            if(md1.equalsIgnoreCase("Desire 820"))
            {
                e3.setIcon(new ImageIcon(""));  c2.setIcon(new ImageIcon(""));co1.setText("500");
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\820c2.jpg"));

            }
            if(md1.equalsIgnoreCase("Desire 501"))
            {e3.setIcon(new ImageIcon("")); c2.setIcon(new ImageIcon(""));co1.setText("400");
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\501c2.jpg"));
            }
            if(md1.equalsIgnoreCase("Desire 601"))
            {e3.setIcon(new ImageIcon("")); c2.setIcon(new ImageIcon(""));co1.setText("450");

                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\601c2.jpg"));
            }
            if(md1.equalsIgnoreCase("Lumia 735"))
            {e3.setIcon(new ImageIcon(""));  c2.setIcon(new ImageIcon(""));co1.setText("300");
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\735c2.jpg"));

            }
            if(md1.equalsIgnoreCase("Lumia 950XL"))
            {e3.setIcon(new ImageIcon(""));  c2.setIcon(new ImageIcon(""));co1.setText("350");

            }

        }            else
        { c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));
 e3.setIcon(new ImageIcon(""));
        }
        }    // TODO add your handling code here:
    }//GEN-LAST:event_c2MouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
sg.setEnabled(true);   hph.setEnabled(true);e3.setIcon(new ImageIcon(""));         c2.setIcon(new ImageIcon());    e.setText("");   
      if(res.getSelectedIndex()>=0){if(cover.isSelected()==true){

            String md1=(String)(res.getSelectedItem());

            if(md1.equalsIgnoreCase("GALAXY S6"))
            {    co1.setText("550");  }
            if(md1.equalsIgnoreCase("GALAXY S5"))
            {     co1.setText("650");
                
            }
            if(md1.equalsIgnoreCase("GALAXY S4"))
            {co1.setText("450");
                
            }
            if(md1.equalsIgnoreCase("iPhone 6s"))
            {co1.setText("850");
                

            }
            if(md1.equalsIgnoreCase("iPhone 5s"))
            { co1.setText("750");
              
            }
            if(md1.equalsIgnoreCase("iPhone 4s"))
            {co1.setText("550");
               

            }
            if(md1.equalsIgnoreCase("Desire 820"))
            {
               co1.setText("550");
                

            }
            if(md1.equalsIgnoreCase("Desire 501"))
            {co1.setText("650");
               
            }
            if(md1.equalsIgnoreCase("Desire 601"))
            {co1.setText("550");

                
            }
            if(md1.equalsIgnoreCase("Lumia 735"))
            {co1.setText("450");
              

            }
            if(md1.equalsIgnoreCase("Lumia 950XL"))
            {co1.setText("350");

            }

        }            else
        { c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));

        }
        } // TODO add your handling code here:
    }//GEN-LAST:event_cMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int head=Integer.parseInt(hp2.getText());int cov=Integer.parseInt(co1.getText());
if(hph.isSelected()){
    if(head==0){
         JOptionPane.showMessageDialog(rootPane, "Please select any one of the headphones");cp.setText("");ca.setText("");
    }
        
        
       
        
    else if(head!=0)
       {
            float a=Integer.parseInt(co1.getText());
float b=Integer.parseInt(hp2.getText());
float cm5=Integer.parseInt(sg1.getText());
ca.setText(""+(a+b+cm5));
float costa=Float.parseFloat(ca.getText());
float costm=Float.parseFloat(cm.getText());
cp.setText((costa+costm)+"");
        }
    if(cover.isSelected()){
        if(cov==0){
    JOptionPane.showMessageDialog(rootPane, "Please select any one of the cases");cp.setText("");ca.setText("");
        }   else if(cov!=0){
        float a=Integer.parseInt(co1.getText());
float b=Integer.parseInt(hp2.getText());
float cm5=Integer.parseInt(sg1.getText());
ca.setText(""+(a+b+cm5));
float costa=Float.parseFloat(ca.getText());
float costm=Float.parseFloat(cm.getText());
cp.setText((costa+costm)+"");
    }
        
    }
    
    
         
    

    
   
         
    
}
else if(cover.isSelected()){
    if(cov==0){
    JOptionPane.showMessageDialog(rootPane, "Please select any one of the cases");cp.setText("");ca.setText("");
        }
    
    else if(cov!=0){
        float a=Integer.parseInt(co1.getText());
float b=Integer.parseInt(hp2.getText());
float cm5=Integer.parseInt(sg1.getText());
ca.setText(""+(a+b+cm5));
float costa=Float.parseFloat(ca.getText());
float costm=Float.parseFloat(cm.getText());
cp.setText((costa+costm)+"");
    }
if(hph.isSelected()){
     if(head==0){
         JOptionPane.showMessageDialog(rootPane, "Please select any one of the headphones");cp.setText("");ca.setText("");
    }
}
   
        
        
       
   
}
    
else {
     float a=Integer.parseInt(co1.getText());
float b=Integer.parseInt(hp2.getText());
float cm5=Integer.parseInt(sg1.getText());
ca.setText(""+(a+b+cm5));
float costa=Float.parseFloat(ca.getText());
float costm=Float.parseFloat(cm.getText());
cp.setText((costa+costm)+"");
}
float costp=Float.parseFloat(cp.getText());
   
 String brand=(String) bd.getSelectedItem();float cover1=Float.parseFloat(co1.getText());
      String model=(String) res.getSelectedItem();float screeng=Float.parseFloat(sg1.getText());
      float costm=Float.parseFloat(cm.getText());float headp=Float.parseFloat(hp2.getText());
      String colo=(String) col.getSelectedItem();
     
      if(costp>50000){
           JOptionPane.showMessageDialog(rootPane,"BRAND - "+brand+"\n"+"MODEL - "+model+"    "+"COLOUR - "+colo+"\n"+"COST OF "+model+"("+colo+")"+"= "+costm+"\n"
        +model+" SCREEN GUARD- "+screeng+" \n"+brand+" "+"HEAD PHONE- "+headp+"\n"+model+" COVER- "+cover1+"\n"+"COST OF THE PRODUCT-"+costp+"Rs \n"+
                   "COST OF THE PRODUCT WITH DISCOUNT-"+(costp-1500)+"RS");
      }
      else{JOptionPane.showMessageDialog(rootPane,"BRAND - "+brand+"\n"+"MODEL - "+model+"    "+"COLOUR - "+colo+"\n"+"COST OF "+model+"("+colo+")"+"= "+costm+"\n"
        +model+" SCREEN GUARD- "+screeng+" \n"+brand+" "+"HEAD PHONE- "+headp+"\n"+model+" COVER- "+cover1+"\n"+"COST OF THE PRODUCT-"+costp+"Rs \n"
                  );
          
      }
// TODO add your handling code hcosta+costmere:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_c2MousePressed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
bill.setText(d+(billno++));
String cname=(String)(cn.getText());
          JOptionPane.showMessageDialog(this,"Thank you "+cname+" \nPlease visit again"); 
    
            cn.setText("");sg.setSelected(false);hph.setSelected(false);cover.setSelected(false);
       cp.setText("");ca.setText("");sg1.setText("0");   hp2.setText("0");  co1.setText("0");
       s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));h1.setIcon(new ImageIcon(""));
       h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));c.setIcon(new ImageIcon(""));
        bd.setSelectedItem("SAMSUNG");cover.setEnabled(true);sg.setEnabled(true);
        hph.setEnabled(true);   float pay=Float.parseFloat(cp.getText());
     
             
       
           
    }//GEN-LAST:event_clearActionPerformed

    private void s1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseClicked
  
        
                   // TODO add your handling code here:
    }//GEN-LAST:event_s1MouseClicked

    private void h3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h3MousePressed
        // TODO add your handling code here:
        cover.setEnabled(true);
    }//GEN-LAST:event_h3MousePressed

    private void h1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h1MousePressed
        // TODO add your handling code here:
        cover.setEnabled(true);
    }//GEN-LAST:event_h1MousePressed

    private void h2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h2MousePressed
        // TODO add your handling code here:
        cover.setEnabled(true);
    }//GEN-LAST:event_h2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NewJFrame3 tech=new  NewJFrame3 ();
        tech.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sgKeyReleased
        s1.setIcon(new ImageIcon(""));// TODO add your handling code here:
    }//GEN-LAST:event_sgKeyReleased

    private void sgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgActionPerformed

    private void sgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sgMouseClicked
        if(res.getSelectedIndex()>=0){if(sg.isSelected()==true){
            String md1=(String)(res.getSelectedItem());ca.setText("");cp.setText("");
            s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6p.jpg"));
            if(md1.equalsIgnoreCase("GALAXY S6"))
            { s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6p.jpg"));
                sg1.setText("300");
            }
            if(md1.equalsIgnoreCase("GALAXY S5"))
            {sg1.setText("250");
                s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss5p.jpg"));
            }
            if(md1.equalsIgnoreCase("GALAXY S4"))
            {sg1.setText("200");
                s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss4pr.jpg"));
            }
            if(md1.equalsIgnoreCase("iPhone 6s"))
            {sg1.setText("500");
                s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6p.jpg"));

            }
            if(md1.equalsIgnoreCase("iPhone 5s"))
            {s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5p.png"));
                sg1.setText("450");}
            if(md1.equalsIgnoreCase("iPhone 4s"))
            {s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4p.jpg"));
                sg1.setText("425");
            }
            if(md1.equalsIgnoreCase("Desire 820"))
            {
                s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6p.jpg"));
                sg1.setText("300");
            }
            if(md1.equalsIgnoreCase("Desire 501"))
            {sg1.setText("200");
                s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6p.jpg"));
            }
            if(md1.equalsIgnoreCase("Desire 601"))
            {sg1.setText("200");

                s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6p.jpg"));
            }
            if(md1.equalsIgnoreCase("Lumia 735"))
            {sg1.setText("250");
                s1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6p.jpg"));

            }
            if(md1.equalsIgnoreCase("Lumia 950XL"))
            {
                sg1.setText("200");
            }

        } else{
            s1.setIcon(new ImageIcon(""));sg1.setText(""+0);
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_sgMouseClicked

    private void sgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sgItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sgItemStateChanged

    private void coverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coverActionPerformed
       if(res.getSelectedIndex()>=0){if(cover.isSelected()==true){ 
 sg.setEnabled(false);

    
    hph.setEnabled(false); ca.setText("");cp.setText("");  c2.setEnabled(true);   c.setEnabled(true);e2.setIcon(new ImageIcon(""));
            e3.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ch1.png"));
            String md1=(String)(res.getSelectedItem());

            if(md1.equalsIgnoreCase("GALAXY S6"))
            { c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6c2.jpg"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6c3.jpg"));          }
            if(md1.equalsIgnoreCase("GALAXY S5"))
            {
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss5c1.jpg"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss5c2.jpg"));
            }
            if(md1.equalsIgnoreCase("GALAXY S4"))
            {
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss4c1.jpg"));

                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss4c3.jpg"));
            }
            if(md1.equalsIgnoreCase("iPhone 6s"))
            {
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6c2.jpg"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6c1.jpg"));

            }
            if(md1.equalsIgnoreCase("iPhone 5s"))
            {c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5c1.jpg"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5c2.jpg"));

            }
            if(md1.equalsIgnoreCase("iPhone 4s"))
            {c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4c1.png"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4c2.jpg"));

            }
            if(md1.equalsIgnoreCase("Desire 820"))
            {
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\820c1.jpg"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\820c2.jpg"));

            }
            if(md1.equalsIgnoreCase("Desire 501"))
            {
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\501c1.jpg"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\501c2.jpg"));

            }
            if(md1.equalsIgnoreCase("Desire 601"))
            {

                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\601c1.jpg"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\601c2.jpg"));

            }
            if(md1.equalsIgnoreCase("Lumia 735"))
            {
                c.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\735c1.jpg"));
                c2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\735c2.jpg"));

            }
            if(md1.equalsIgnoreCase("Lumia 950XL"))
            {

            }

        }            else{ c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));hph.setEnabled(true);sg.setEnabled(true);
            c.setEnabled(false);   c2.setEnabled(false); e3.setIcon(new ImageIcon(""));co1.setText("0");
            if(hph.isSelected()){
                e2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ch.png"));
            }
            else{
                  e2.setIcon(new ImageIcon(""));
            }
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_coverActionPerformed

    private void hphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hphActionPerformed

        if(res.getSelectedIndex()>=0){if(hph.isSelected()==true){
   sg.setEnabled(false);

    
    cover.setEnabled(false);
 h1.setEnabled(true);h2.setEnabled(true);h3.setEnabled(true);hp1.setVisible(true);ca.setText("");cp.setText("");
            e2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ch.png"));
            String md1=(String)(bd.getSelectedItem());

            if(md1.equalsIgnoreCase("apple"))
            { h1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\b.jpg"));
                h2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\r.jpg"));
                h3.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\g.jpg"));}
            if(md1.equalsIgnoreCase("htc"))
            {
                h1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\db.jpg"));
                h2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\y.jpg"));
                h3.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\p.jpg")); }
            if(md1.equalsIgnoreCase("samsung"))
            {
                h1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\b.jpg"));
                h2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\p.jpg"));
                h3.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\g.jpg")); }
            if(md1.equalsIgnoreCase("microsoft"))
            {
                h1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\db.jpg"));
                h2.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\y.jpg"));
h3.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\p.jpg"));
            }

        }            else{ hp1.setIcon(new ImageIcon(""));h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
            h2.setEnabled(false);h1.setEnabled(false);h2.setEnabled(false);h3.setEnabled(false);hp2.setText("0");cover.setEnabled(true);sg.setEnabled(true);
            e2.setIcon(new ImageIcon(""));hp1.setVisible(false);
        }
        }
    }//GEN-LAST:event_hphActionPerformed

    private void colActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colActionPerformed
cp.setText("");        if(col.getSelectedIndex()>=0){
            String col1=(String)(col.getSelectedItem());
            String md1=(String)(res.getSelectedItem());

            if(md1.equalsIgnoreCase("GALAXY S6")){
                if(col1.equalsIgnoreCase("WHITE")){cm.setText("50000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6w.jpg"));
                } if(col1.equalsIgnoreCase("BLACK")){cm.setText("50500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6b.jpg"));
                } if(col1.equalsIgnoreCase("SILVER")){cm.setText("51000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss6g.jpg"));
                }

            }
            if(md1.equalsIgnoreCase("GALAXY S4")){
                if(col1.equalsIgnoreCase("WHITE")){cm.setText("30000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss4w.jpeg"));
                } if(col1.equalsIgnoreCase("BLACK")){cm.setText("30500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss4b.jpeg"));
                } if(col1.equalsIgnoreCase("PURPLE")){cm.setText("31000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss4p.jpg"));
                }

            }
            if(md1.equalsIgnoreCase("GALAXY S5"))
            {
                if(col1.equalsIgnoreCase("WHITE")){cm.setText("45000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss5w.jpg"));
                } if(col1.equalsIgnoreCase("BLACK")){cm.setText("45500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\ss5b.png"));
                }

            }

            if(md1.equalsIgnoreCase("iPhone 6s"))
            {
                if(col1.equalsIgnoreCase("WHITE")){cm.setText("60000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6sw.jpg"));
                } if(col1.equalsIgnoreCase("GOLD")){cm.setText("60500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6sg.jpg"));
                } if(col1.equalsIgnoreCase("ROSE")){cm.setText("61000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6sr.jpg"));
                }

            }
            if(md1.equalsIgnoreCase("iPhone 5s"))
            {
                if(col1.equalsIgnoreCase("gold")){cm.setText("48000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5g.jpeg"));
                } if(col1.equalsIgnoreCase("BLue")){cm.setText("48500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5b.jpeg"));
                } if(col1.equalsIgnoreCase("white")){cm.setText("49000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5w.jpg"));
                }

            }
            if(md1.equalsIgnoreCase("iPhone 4s"))
            {
                if(col1.equalsIgnoreCase("WHITE")){cm.setText("35000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4w.jpg"));
                } if(col1.equalsIgnoreCase("BLACK")){cm.setText("35500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4b.png"));
                }

            }
            if(md1.equalsIgnoreCase("Desire 820")){
                if(col1.equalsIgnoreCase("WHITE")){cm.setText("20000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\820w.jpg"));
                } if(col1.equalsIgnoreCase("BLACK")){cm.setText("20500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\820b.jpg"));
                } if(col1.equalsIgnoreCase("blue")){cm.setText("20100");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\820bl.jpg"));
                }

            }
            if(md1.equalsIgnoreCase("Desire 501"))
            {
                if(col1.equalsIgnoreCase("WHITE")){cm.setText("15000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\501w.jpg"));
                } if(col1.equalsIgnoreCase("BLACK")){cm.setText("15500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\501b.png"));
                }
                if(col1.equalsIgnoreCase("Pink")){cm.setText("16000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\501p.jpeg"));
                }

            }

            if(md1.equalsIgnoreCase("Desire 601"))
            {
                if(col1.equalsIgnoreCase("WHITE")){cm.setText("22000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\601w.jpg"));
                } if(col1.equalsIgnoreCase("black")){cm.setText("22500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\601bla.jpg"));
                } if(col1.equalsIgnoreCase("blue")){cm.setText("23000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\601b.jpg"));
                }

            }
            if(md1.equalsIgnoreCase("Lumia 735"))
            {
                if(col1.equalsIgnoreCase("orange")){cm.setText("13000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\lumia735o.png"));
                } if(col1.equalsIgnoreCase("green")){cm.setText("13500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\lumia735g.jpg"));
                } if(col1.equalsIgnoreCase("black")){cm.setText("14000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\lumia735b.png"));
                }

            }
            if(md1.equalsIgnoreCase("Lumia 950xl"))
            {
                if(col1.equalsIgnoreCase("blue")){cm.setText("25000");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\l950xlb.jpg"));
                } if(col1.equalsIgnoreCase("BLACK")){cm.setText("25500");
                    c1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\l950xlbla.jpg"));
                }

            }
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_colActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
ca.setText("");     ne.setEnabled(true);  ba.setEnabled(false);
      co1.setText("");e2.setIcon(new ImageIcon(""));hp2.setText("");sg1.setText("");if(res.getSelectedIndex()>=0){col.removeAllItems();
            String md1=(String)(res.getSelectedItem());

            if(md1.equalsIgnoreCase("GALAXY S6"))
            {
                c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon("")); sg.setSelected(false);cover.setSelected(false);
                hph.setSelected(false);s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));
                h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
                col.addItem("WHITE");
                col.addItem("BLACK");sg1.setText("0");   hp2.setText("0");  co1.setText("0");
                col.addItem("SILVER");cm.setText("50000"); des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rg.png"));
            }
            if(md1.equalsIgnoreCase("GALAXY S5"))
            {  c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon("")); sg.setSelected(false);
                cover.setSelected(false);hph.setSelected(false);s1.setIcon(new ImageIcon(""));
                hp1.setIcon(new ImageIcon(""));h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));
                h3.setIcon(new ImageIcon(""));
                col.addItem("WHITE");sg1.setText("0");   hp2.setText("0");  co1.setText("0");
                col.addItem("BLACK");cm.setText("45000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s5rg.png"));
            }
            if(md1.equalsIgnoreCase("GALAXY S4"))
            { c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));sg.setSelected(false);
                cover.setSelected(false);hph.setSelected(false);s1.setIcon(new ImageIcon(""));
                hp1.setIcon(new ImageIcon(""));h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));
                h3.setIcon(new ImageIcon(""));
                col.addItem("WHITE");
                col.addItem("BLACK");sg1.setText("0");   hp2.setText("0");  co1.setText("0");
                col.addItem("PURPLE");cm.setText("30000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s4rg.png"));
            }
            if(md1.equalsIgnoreCase("iPhone 6s"))
            {
                c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));sg.setSelected(false);
                cover.setSelected(false);hph.setSelected(false);s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));
                h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
                col.addItem("WHITE");
                col.addItem("GOLD");sg1.setText("0");   hp2.setText("0");  co1.setText("0");
                col.addItem("ROSE");cm.setText("60000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6srg.png"));
            }
            if(md1.equalsIgnoreCase("iPhone 5s"))
            {c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon("")); sg.setSelected(false);cover.setSelected(false);
                hph.setSelected(false);s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));
                h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
                col.addItem("GOLD");col.addItem("BLUE");
                col.addItem("WHITE");cm.setText("48000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5srg.png"));
           sg1.setText("0");   hp2.setText("0");  co1.setText("0"); }
            if(md1.equalsIgnoreCase("iPhone 4s"))
            { c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon("")); sg.setSelected(false);cover.setSelected(false);
                hph.setSelected(false);s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));h1.setIcon(new ImageIcon(""));
                h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
                col.addItem("WHITE");
                col.addItem("BLACK");cm.setText("35000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4srg.png"));
sg1.setText("0");   hp2.setText("0");  co1.setText("0");
            }
            if(md1.equalsIgnoreCase("Desire 820"))
            {c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));sg.setSelected(false);
                cover.setSelected(false);hph.setSelected(false);s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));
                h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
sg1.setText("0");   hp2.setText("0");  co1.setText("0");
                col.addItem("WHITE");
                col.addItem("BLACK");
                col.addItem("BLUE");cm.setText("20000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rg.png"));
            }
            if(md1.equalsIgnoreCase("Desire 501"))
            {c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));sg.setSelected(false);cover.setSelected(false);
                hph.setSelected(false);s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));h1.setIcon(new ImageIcon(""));
                h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
                col.addItem("WHITE");
                col.addItem("BLACK");col.addItem("PINK");cm.setText("15000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rg.png"));
            }
            if(md1.equalsIgnoreCase("Desire 601"))
            {c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));sg.setSelected(false);
                cover.setSelected(false);hph.setSelected(false);s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));
                h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
                col.addItem("WHITE");
                col.addItem("BLACK");cm.setText("22000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rg.png"));
sg1.setText("0");   hp2.setText("0");  co1.setText("0");
            }
            if(md1.equalsIgnoreCase("Lumia 735"))
            {
                c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));sg.setSelected(false);cover.setSelected(false);
                hph.setSelected(false);s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));h1.setIcon(new ImageIcon(""));
                h2.setIcon(new ImageIcon(""));h3.setIcon(new ImageIcon(""));
                col.addItem("ORANGE");
                col.addItem("GREEN");sg1.setText("0");   hp2.setText("0");  co1.setText("0");
                col.addItem("BLACK");cm.setText("13000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rg.png"));
            }
            if(md1.equalsIgnoreCase("Lumia 950XL"))
            {c.setIcon(new ImageIcon(""));c2.setIcon(new ImageIcon(""));sg.setSelected(false);cover.setSelected(false);hph.setSelected(false);
                s1.setIcon(new ImageIcon(""));hp1.setIcon(new ImageIcon(""));h1.setIcon(new ImageIcon(""));h2.setIcon(new ImageIcon(""));
                h3.setIcon(new ImageIcon(""));
                col.addItem("BLACK");sg1.setText("0");   hp2.setText("0");  co1.setText("0");
                col.addItem("BLUE");cm.setText("25000");des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rg.png"));
            }

        }
    }//GEN-LAST:event_resActionPerformed

    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
        e2.setText("");      if(bd.getSelectedIndex()>=0){res.removeAllItems();
            String bd1=(String)(bd.getSelectedItem());

            if(bd1.equalsIgnoreCase("samsung"))
            {

                res.addItem("GALAXY S6");
                res.addItem("GALAXY S5");
                res.addItem("GALAXY S4");
            }
            if(bd1.equalsIgnoreCase("apple"))
            {
                res.addItem("iPhone 6s");
                res.addItem("iPhone 5s");
                res.addItem("iPhone 4s");
            }
            if(bd1.equalsIgnoreCase("htc"))
            {
                res.addItem("Desire 820");
                res.addItem("Desire 501");
                res.addItem("Desire 601");
            }
            if(bd1.equalsIgnoreCase("microsoft"))
            {
                res.addItem("Lumia 735");
                res.addItem("Lumia 950XL");
            }
        }

    }//GEN-LAST:event_bdActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billActionPerformed

    private void neActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neActionPerformed
  ba.setEnabled(true);String md1=(String)(res.getSelectedItem());

            if(md1.equalsIgnoreCase("GALAXY S6"))
            { des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rh.png"));
                
            }
            if(md1.equalsIgnoreCase("GALAXY S5"))
            {  des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s5rh.png"));
            }
            if(md1.equalsIgnoreCase("GALAXY S4"))
            { des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s4rh.png"));
            }
            if(md1.equalsIgnoreCase("iPhone 6s"))
            {
               des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6srh.png"));
            }
            if(md1.equalsIgnoreCase("iPhone 5s"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5src.png"));
            }
            if(md1.equalsIgnoreCase("iPhone 4s"))
            { des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4srh.png"));

            }
            if(md1.equalsIgnoreCase("Desire 820"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\820rh.png"));
            }
            if(md1.equalsIgnoreCase("Desire 501"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\501rh.png"));
            }
            if(md1.equalsIgnoreCase("Desire 601"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\601rh.png"));

            }
            if(md1.equalsIgnoreCase("Lumia 735"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\735rh.png"));
                
            }
            if(md1.equalsIgnoreCase("Lumia 950XL"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\950rh.png"));
            }
ne.setEnabled(false);
               // TODO add your handling code here:
    }//GEN-LAST:event_neActionPerformed

    private void baActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baActionPerformed
     ne.setEnabled(true);String md1=(String)(res.getSelectedItem());

            if(md1.equalsIgnoreCase("GALAXY S6"))
            { des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s6rg.png"));
                
            }
            if(md1.equalsIgnoreCase("GALAXY S5"))
            {  des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s5rg.png"));
            }
            if(md1.equalsIgnoreCase("GALAXY S4"))
            { des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\s4rg.png"));
            }
            if(md1.equalsIgnoreCase("iPhone 6s"))
            {
               des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i6srg.png"));
            }
            if(md1.equalsIgnoreCase("iPhone 5s"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i5srg.png"));
            }
            if(md1.equalsIgnoreCase("iPhone 4s"))
            { des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\i4srg.png"));

            }
            if(md1.equalsIgnoreCase("Desire 820"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\820rg.png"));
            }
            if(md1.equalsIgnoreCase("Desire 501"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\501rg.png"));
            }
            if(md1.equalsIgnoreCase("Desire 601"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\601rg.png"));

            }
            if(md1.equalsIgnoreCase("Lumia 735"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\735rg.png"));
                
            }
            if(md1.equalsIgnoreCase("Lumia 950XL"))
            {des1.setIcon(new ImageIcon("C:\\Users\\HomePC\\Documents\\NetBeansProjects\\JavaApplication3\\src\\imagestech\\950rg.png"));
            }
ba.setEnabled(false);
    }//GEN-LAST:event_baActionPerformed

    private void hp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hp2ActionPerformed

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed

    }//GEN-LAST:event_cpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tech().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acc;
    private javax.swing.JButton ba;
    private javax.swing.JComboBox bd;
    private javax.swing.JTextField bill;
    private javax.swing.JLabel c;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JTextField ca;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cm;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField co1;
    private javax.swing.JComboBox col;
    private javax.swing.JCheckBox cover;
    private javax.swing.JTextField cp;
    private javax.swing.JLabel des1;
    private javax.swing.JLabel e;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel hp1;
    private javax.swing.JTextField hp2;
    private javax.swing.JCheckBox hph;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton ne;
    private javax.swing.JComboBox res;
    private javax.swing.JLabel s1;
    private javax.swing.JCheckBox sg;
    private javax.swing.JTextField sg1;
    // End of variables declaration//GEN-END:variables
}
